Libraries:


In [4]:
import numpy as np
import math

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
# Eigenvalues
M = np.array([[26,18],
              [18,74]])

vals, vecs = np.linalg.eig(M)
print(vals)
print('\n',vecs)

# print('\n',[-3/math.sqrt(10), 1/math.sqrt(10)])

In [1]:
# Eigenvectors - Note, the eigenvectors are the columns of the output.
M = np.array([[5, -5],
              [-1, 2],
              [7, 6]])
vals, vecs = np.linalg.eig(M)
vecs 



LinAlgError: Last 2 dimensions of the array must be square

Eigen values aren't defined of rec. Matrices<br/>
why?<br/>
Non square cannot satisfy  Ax=λx <br/>
Because the two sides are vectors of different dimensions.

### Examples

In [ ]:
#getting i/p matrix from user
print("For calculating Eigen values, pls input a sq.Matrix")


R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 

matrix = [] 
print("Enter the entries rowwise:") 

# user input 
for i in range(R):
    a =[] 
    for j in range(C): 
        a.append(int(input())) 
    matrix.append(a) 

print("The Matrix is:")
# printing the matrix 
for i in range(R): 
    for j in range(C): 
        print(matrix[i][j], end = " ") 
    print() 

evals, evecs = np.linalg.eig(matrix)

print("\nThe eigen values are:",evals)
print("\nThe eigen vectors are:",evecs)




In [5]:
#180 deg rotation
F = np.array([[-1,0],
             [0,-1]])
vals, vecs = np.linalg.eig(F)
vals

vecs

array([-1., -1.])

array([[1., 0.],
       [0., 1.]])

In [7]:
#90 degree roatation
G =  np.array([[0,-1],
               [1,0]])
vals , vecs = np.linalg.eig(G)
vals

vecs

array([0.+1.j, 0.-1.j])

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]])

In [8]:
J = np.array([[3,0],
              [1,2]])
vals , vecs = np.linalg.eig(J)
vals

vecs
#more on dysmo

array([2., 3.])

array([[0.        , 0.70710678],
       [1.        , 0.70710678]])

In [ ]:
M = np.array([[0, 1, 0,0],
              [1, 0, 0,0],
              [0, 0, 0,1],
              [0,0,1,0]])
vals, vecs = np.linalg.eig(M)
vals

vecs

In [ ]:
M = np.array([[1.5,-1],
              [-0.5,0.5]])
vals, vecs = np.linalg.eig(M)
vals

vecs

#### Eigen values of Symmetric Matrices
The eigenvalues of a symmetric matrix are always real and the eigenvectors are always orthogonal! 

In [1]:
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
matrix = [] 
print("Enter the entries rowwise:") 

# user input 
for i in range(R):
    a =[] 
    for j in range(C): 
        a.append(float(input())) 
    matrix.append(a) 

print("The Matrix is:")
# printing the matrix 
for i in range(R): 
    for j in range(C): 
        print(matrix[i][j], end = " ") 
    print() 
        
# A = np.cov(matrix)
# A

Enter the number of rows:3
Enter the number of columns:2
Enter the entries rowwise:
3
4
8
4
7
10
The Matrix is:
3.0 4.0 
8.0 4.0 
7.0 10.0 


In [1]:
n = 3
A = np.random.randint(0,10,(n,n))
A

S = A @ A.T
S

array([[94, 37, 65],
       [37, 69, 22],
       [65, 22, 50]])

In [2]:
vals, vecs = np.linalg.eig(S)

vals  # real values?

vecs

array([[-0.74169257, -0.59902368,  0.30176606],
       [-0.42396203,  0.07005542, -0.90296646],
       [-0.51975795,  0.79766087,  0.30592289]])

Check for orthogonality:

In [3]:
#taking the first column of first egn vect
v1 = vecs[:,0]
v1

array([-0.74169257, -0.42396203, -0.51975795])

In [4]:
#second column
v2 = vecs[:,1]
v2

array([-0.59902368,  0.07005542,  0.79766087])

In [5]:
#v1.v2 is orthogonal?

v1 @ v2

#almost equals to zero.

3.8163916471489756e-17

When we project data onto orthogonal basis,the CoVar is scaked(while using PCA)--> we are trying to make the columns Independent.