## Machine Learning - Session 1 - NumPy

In [2]:
#Import the numpy library
import numpy as np

#### A. Defining a 1D numpy array

In [1]:
L = [10.,12,13,45,78,89,25]

In [4]:
type(L)

list

In [6]:
x = np.array(L)
x

array([10., 12., 13., 45., 78., 89., 25.])

In [7]:
type(x)

numpy.ndarray

#### B. Creating Regular Sequence

In [9]:
#Create a regular sequence of integers starting from 1 to 10. integers = c(1,2,3,4,.......,10)
a = np.arange(1,11,1) #this is a fn in np, not a method, lastno. is not inc
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Create a regular sequence of integers starting from 10 to 1.
b = np.arange(10,0,-1)
b

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [11]:
#Create a regular sequence of even integers between 10 to 20
even = np.arange(10,21,2) #incrementing by 2 gives even no.
even


array([10, 12, 14, 16, 18, 20])

In [12]:
#Create a regular sequence of the following type: [10.0,10.5,11.0,11.5, ... , 19.5, 20.0]
seq = np.arange(10,21,0.5)
seq

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [13]:
#Create a regular sequence of length 20 ranging from 0 to 5
r = np.linspace(start=0,stop=5,num=20,endpoint = True)  #divides 0 to 5 by 20 and gives 20 equal parts
r  #regular seq  #endpoint = true includes stop value

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [14]:
#Help for np.linspace

help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [15]:
#Studying the arange function

help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

#### C. Creating a Random Sequence

In [19]:
#Generate 20 random numbers between 1 and 100 with replacements
np.random.seed(0) #we use this to replciate an experiment, we got same random no. like sir.
a = np.random.randint(1,100,20)  #it helps to generate multiple random no. unlike normal-randint
a

array([82, 38, 26, 78, 73, 10, 21, 81, 70, 80, 48, 65, 83, 89, 50, 30, 20,
       20, 15, 40])

In [22]:
np.random.seed(0)
b = np.random.random(20)
b

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [26]:
#Shuffle the vector x
print(L)
x = np.array(L)
np.random.shuffle(x)  #everytime we run it , it shuffles
x

[10.0, 12, 13, 45, 78, 89, 25]


array([89., 13., 25., 78., 12., 10., 45.])

In [29]:
np.random.choice(L,2)   #radomnly selects 2 values from L

array([78., 45.])

In [30]:
#random sampling 
s=np.random.choice(L,15,replace =True )
s #sampling is done with repalcement,like in probabality selecting a card 
#and replacing it in pack and again selecting it

array([25., 45., 13., 78., 13., 10., 10., 78., 89., 89., 25., 10., 78.,
       12., 78.])

In [35]:
d=np.random.choice(L,5,replace = False )#without replacement
d  #main note- sampling size should be less than the population or it wont be logical.

array([78., 12., 89., 10., 25.])

In [7]:
#Permute x and return it
np.random.permutation(10)

array([6, 5, 1, 2, 8, 7, 0, 3, 4, 9])

To find more on numpy random sampling Go To this link 
https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.random.html 

#### D. Some basic numpy methods

In [46]:
x = np.array([12,34,24,45,7,18])
x

array([12, 34, 24, 45,  7, 18])

In [37]:
#Size of the array
x.size  #size is faster than len fn, size uses vectorize method.

6

In [38]:
#data type
x.dtype

dtype('int32')

In [39]:
#Type of the object
type(x)

numpy.ndarray

In [49]:
#Type conversion
x = x.astype(str)

In [50]:
x.dtype

dtype('<U11')

#### E. Some basic (1D) numpy operations

In [8]:
#Consider that we have two arrays

x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [52]:
#Addition
x+y

array([15, 40, 32, 50,  8, 28])

In [53]:
#Subtraction
x-y

array([ 9, 28, 16, 40,  6,  8])

In [54]:
#Multiplication by scalar
10*y

array([ 30,  60,  80,  50,  10, 100])

In [55]:
y*(1/10)

array([0.3, 0.6, 0.8, 0.5, 0.1, 1. ])

In [56]:
y/10

array([0.3, 0.6, 0.8, 0.5, 0.1, 1. ])

In [57]:
#Element wise multiplication (dot product)
x*y

array([ 36, 204, 192, 225,   7, 180])

In [58]:
#Using dot method
x @ y

844

In [59]:
np.sum(x*y)

844

In [60]:
x.dot(y)

844

In [61]:
#Squaring each elements in an array
x**2

array([ 144, 1156,  576, 2025,   49,  324], dtype=int32)

In [64]:
x**(1/2)

array([3.46410162, 5.83095189, 4.89897949, 6.70820393, 2.64575131,
       4.24264069])

In [63]:
np.sqrt(x)

array([3.46410162, 5.83095189, 4.89897949, 6.70820393, 2.64575131,
       4.24264069])

In [65]:
np.exp(x)

array([1.62754791e+05, 5.83461743e+14, 2.64891221e+10, 3.49342711e+19,
       1.09663316e+03, 6.56599691e+07])

In [66]:
np.log(x)

array([2.48490665, 3.52636052, 3.17805383, 3.80666249, 1.94591015,
       2.89037176])

#### F. Some Useful Numpy Functions

In [67]:
y = np.array([3,6,8,5,1,10])

In [68]:
#Sum
np.sum(y)

33

In [69]:
sum(y)  #they are really not same

33

In [70]:
#Mean
np.mean(y)

5.5

In [71]:
#Standard Deviation
np.std(y)

2.9860788111948193

In [72]:
#Minimum
np.min(y)

1

In [73]:
#Maximum
np.max(y)

10

In [74]:
#Percentiles
#60th percentile
np.percentile(y,60)

6.0

In [75]:
np.percentile(y,[20,60,75])  #different percentiles are passed as an array

array([3. , 6. , 7.5])

In [76]:
#Sorting
np.sort(y)  #always sorts in ascending order

array([ 1,  3,  5,  6,  8, 10])

In [80]:
#for descending sort
print(-y)
-np.sort(-y) #multiply again with (-)

[ -3  -6  -8  -5  -1 -10]


array([10,  8,  6,  5,  3,  1])

#### G. Subsetting a 1D numpy array

In [3]:
x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [82]:
#Subsetting and slicing is same as list
x[0]

12

In [83]:
x[1]

34

In [84]:
x[3:5]

array([45,  7])

In [85]:
x[[2,4]]  #for 2nd and 4th element without slicing

array([24,  7])

#### H. Conditional Subsetting

**The Comparison Operators**

      > is greater than
      < is less than
      == is equal to
      <= is less than equal to
      >= is greater than equal to

In [4]:
x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [87]:
2 > 30 #always gives boolean value

False

In [88]:
x > 20  #gives u array of true or false, checks each and every element

array([False,  True,  True,  True, False, False])

# Important use in DS

In [89]:
np.sum(x > 20)  #checks the whole column, and returns the count where the sum is > 20 

3

**The Logical Operators**

    AND: &
    OR : |

In [91]:
(x> 30) & (x <10)

array([False, False, False, False, False, False])

In [92]:
(x>30) | (x<10)

array([False,  True, False,  True,  True, False])

**Problems**

In [5]:
#Consider the following two vectors

x = np.array([33,45,23,67,54,48])
y = np.array([108,151,164,119,135,122])

In [98]:
x < 35 #values of x less than 35 #it is not correct

array([ True, False,  True, False, False, False])

In [99]:
np.logical_not(x<35)

array([False,  True, False,  True,  True,  True])

In [100]:
#a. Vaues of x that are less than 35
x[x<35]  #np helps u solve without for loop.


array([33, 23])

In [8]:
#b. The number of observations in y that are more than 150
print(y[y>150])
y[y>150].size

[151 164]


2

In [6]:
#or we can do like
sum(y > 150) #best way to program

2

In [12]:
#c. The number of observations in y that are between 120 and 165
sum((y>=120) & (y<=165)) #if we need no. of obeseravation 
#we can use sum fn.


4

In [14]:
#d. The vaues in x that are less than 30 or greater than 50
x[((x<30) | (x >50))] 

array([23, 67, 54])

In [19]:
#e. The values in x for which the values in y is less than or equal to 120
x[y<=120]

array([12, 34, 24, 45,  7, 18])

In [15]:
#f. The values in y for which the values in x is equal to 45
y[x==45]

array([151])

#### I. Defining a 2D numpy array

In [18]:
#Converting a 1D array into 2D array
x = np.array([33,45,23,67,54,48])

matrix = x.reshape(2,3)
matrix

array([[33, 45, 23],
       [67, 54, 48]])

In [19]:
m = x.reshape(3,2)
m

array([[33, 45],
       [23, 67],
       [54, 48]])

In [25]:
#Create a 3x3 matrix containing elements from 1 to 9
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.eye(3)  #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
#Joining two 1D arrays to form a matrix
x = np.array([33,45,23,67,54,48])
y = np.array([108,151,164,119,135,122])

m = np.array([x,y])
print(m)

print('\n',np.transpose(m))
#or
print('\n',np.reshape([x,y],(6,2)))
#or
print('\n', np.append(x,y).reshape(6,2))

[[ 33  45  23  67  54  48]
 [108 151 164 119 135 122]]

 [[ 33 108]
 [ 45 151]
 [ 23 164]
 [ 67 119]
 [ 54 135]
 [ 48 122]]

 [[ 33  45]
 [ 23  67]
 [ 54  48]
 [108 151]
 [164 119]
 [135 122]]

 [[ 33  45]
 [ 23  67]
 [ 54  48]
 [108 151]
 [164 119]
 [135 122]]



#### J. Some basic methods for 2D numpy array

In [43]:
matrix = np.array([[38,33,47],
                    [29,48,35],
                    [21,34,47],
                    [38,44,21],
                    [28,26,43]])
matrix

array([[38, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [45]:
#Checking the shape of the matrix
matrix.shape

(5, 3)

In [52]:
#Dimension of the array
matrix.ndim

2

In [46]:
#Data type of the elements in the array
matrix.dtype

dtype('int32')

In [53]:
matrix.dtype.name

'int32'

In [47]:
#Number of elements present in the matrix
matrix.size

15

In [54]:
#Size of the matrix in bytes
matrix.itemsize

4

In [103]:
matrix.nbytes # gives u itemsize * matrix size => 4 * 15


60

#### K. Subsetting 2D numpy array

In [55]:
#matrix
matrix = np.array([[38,33,47],
                    [29,48,35],
                    [21,34,47],
                    [38,44,21],
                    [28,26,43]])
matrix


array([[38, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [56]:
#a) Print the first element of the matrix.
matrix[0,0]


38

In [60]:
matrix.shape

(5, 3)

In [62]:
matrix.shape[0]-1 #this gve rows 
#-1, bcoz py starts indexing at 0 
#getting the last row (count) 
#.shape tells us shape(5,3),so 5-1 ,
#gives 4th row thats the last row


4

In [63]:
matrix.shape[1]-1 #columns

2

In [57]:
#b) Print the last element of the matrix.
matrix[matrix.shape[0]-1,matrix.shape[1]-1] #best practice

43

In [59]:
#Or
print(matrix[-1,-1])
#or
print(matrix[4,2]) #hard coding- u knw shape and doing

43
43


In [69]:
#c) Print the values of the first row.
matrix[0,:]

array([38, 33, 47])

In [66]:
#d) Print the values of the fourth row.
matrix[matrix.shape[0]-1]

array([28, 26, 43])

In [68]:
#e) Print the values first column.
matrix[:,0]

array([38, 29, 21, 38, 28])

In [73]:
matrix[2,]

array([21, 34, 47])

In [72]:
#f) Calculate the total of the third row.
np.sum(matrix[2,:]) #without colon also it will work, 
#but while perfroming colmn operation , it will throw error

102

In [75]:
#g) Calculate the total of the fifth row.
np.sum(matrix[4,:])

97

In [77]:
#h) Calculate the total of the second column.
np.sum(matrix[:,1])

185

In [89]:
#i) Calculate the average of the values of the first row.
avg = np.average(matrix[0,:])
avg

39.0

In [80]:
#j) Replace the first value of the matrix by 50.
matrix[0,0] = 50
matrix


array([[50, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [86]:
#k) Replace the last value of the matrix by 30.
matrix[matrix.shape[0]-1,matrix.shape[1]-1] = 30
matrix

array([[50, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 30]])

In [88]:
#l) Replace the second column of the matrix by the vector (20,30,20,30,20)
matrix[:,1] = [20,30,20,30,20]
matrix


array([[50, 20, 47],
       [29, 30, 35],
       [21, 20, 47],
       [38, 30, 21],
       [28, 20, 30]])

In [92]:
#m) Replace the first row of the matrix by the vector its average (calculated above).

matrix[0,:] = np.average(matrix)
matrix


array([[29, 29, 29],
       [29, 30, 35],
       [21, 20, 47],
       [38, 30, 21],
       [28, 20, 30]])

In [100]:
#q) Calculate the sum of all the elements of the matrix
np.sum(matrix)

436

In [98]:
#r) Calculate the sum of all the rows on the matrix
np.sum(matrix[:,])

436

In [99]:
#s) Calculate the sum of all the colummns of the matrix
np.sum(matrix[:,:])

436

#### L. Matrix Operations

In [107]:
#Defining a matrix 'm'
m = np.array([[2,3],[4,5]])
m

array([[2, 3],
       [4, 5]])

In [108]:
#Defining a matrix 'n'
n = np.array([[1,0],[3,6]])
n

array([[1, 0],
       [3, 6]])

In [105]:
#Multiplication by scalar
2*n

array([[ 2,  0],
       [ 6, 12]])

In [109]:
#Matrix addition
m + n

array([[ 3,  3],
       [ 7, 11]])

In [114]:
#Matrix Multilication
x =m.dot(n)
print(x)
#or
y = np.dot(m,n)
print(y)

[[11 18]
 [19 30]]
[[11 18]
 [19 30]]


In [111]:
#Preferred - for Matrix Multilication
np.matmul(m,n)

array([[11, 18],
       [19, 30]])

In [112]:
#Preferred - for Matrix Multilication
m @ n

array([[11, 18],
       [19, 30]])

In [113]:
#Element-wise array multilication
np.multiply(m,n)

array([[ 2,  0],
       [12, 30]])

#### Copying data

In [115]:
p = np.array([2,5,8,6])

In [116]:
q = p #note the not new obj is created
#this is just aliasing, #or rename

In [117]:
q

array([2, 5, 8, 6])

In [120]:
q[2] = 10
q

array([ 2,  5, 10,  6])

In [121]:
p #changes reflecting here as well

array([ 2,  5, 10,  6])

In [122]:
q = p.copy()   #this is how u copy

In [123]:
q[2] = 100
q

array([  2,   5, 100,   6])

In [124]:
p

array([ 2,  5, 10,  6])